version: '3.8'
services:
  # Base de données H2 (en mémoire)
  db:
    image: h2:1.4.204
    ports:
      - "8082:8082"
    environment:
      H2_OPTIONS: "-tcp -tcpAllowOthers -tcpPort 8082"

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passer
    command: start-dev

  # Vault
  vault:
    image: vault:1.12.3
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK

  # Application Spring Boot
  api:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
      - keycloak
      - vault
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://db:8082/mem:bank-db
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID: bank-digital
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: ecpex74Bv6sEm1ebiF3pcc6z7wLoBZl9
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/umoa-realm
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
